# Generated by Django 5.2 on 2025-05-18 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='category',
            new_name='app_categor_store_i_732e1f_idx',
            old_name='app_categ_store_i_372742_idx',
        ),
    ]
