# Generated by Django 5.2 on 2025-05-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('buyer', 'Покупатель'), ('store_owner', 'Владелец магазина')], default='buyer', max_length=20),
        ),
    ]
