# Generated by Django 5.2 on 2025-05-08 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosi', '0002_store_alter_product_subcategory_category_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosi.store'),
        ),
    ]
